.travis.yml, Makefile, Scripts/Dockerfile-testing-linux, Scripts/develop-linux-docker.sh, Scripts/run-tests-linux-docker.sh
Add docker for development and testing. Add Travis CI configuration.
Closes #7
=> Add Travis CI

Makefile, Scripts/Dockerfile-testing-linux, Scripts/integration-tests.py
=> Add integration tests

Sources/treCore/File+Formatting.swift, Sources/treCore/PathProvider.swift, Sources/treCore/execute.swift
This improves performance about 25%
=> Improve performance

Sources/treCore/File+Formatting.swift
=> Add more speed

Makefile, src/file_tree.rs, src/formatting.rs, src/output.rs, src/path_finders.rs, src/tre.rs
- Don't use `Option.unwrap()`
- use `&str` whenever possible.
=> Use better Rust patterns

README.md, src/cli.rs, src/output.rs, src/tre.rs
=> Add editor alias support for Windows PowerShell

CHANGELOG.md, src/cli.rs, src/path_finders.rs, src/tre.rs
=> Add option to show directory only

.github/workflows/automerge.yml, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, Makefile, README.md
I have feeling I've been on this path before.
I hope this works...
=> Use [[bin]] to specify executable name

src/cli.rs, src/path_finders.rs, src/tre.rs
=> Add option to limit display depth

.github/workflows/ci.yml, CHANGELOG.md, Makefile, scripts/check-version.py
Use CI to catch unbumped version
=> Check version inconsistency

README.md
=> Add installation instruction for NetBSD

README.md
Use a table to be more succinct.
=> Update installation description

README.md
=> Update netbsd instruction

README.md
=> Include -S for yay install instruction

.gitignore, flake.nix
... instead of importing from nixpkgs
=> Embed nix build logic

flake.nix, scripts/check-version.py
One fewer thing to go out-of-sync.
=> Read version from Cargo.toml to flake.nix

CHANGELOG.md, manual/tre.1, src/cli.rs, src/output.rs, src/tre.rs
Closes #101.
Also includes some slight performance improvement.
=> Add -c/--color option

CHANGELOG.md, scripts/completion/_tre, scripts/completion/_tre.ps1, scripts/completion/tre.bash, scripts/completion/tre.elv, scripts/completion/tre.fish, src/cli.rs, src/diagram_formatting.rs, src/tre.rs
=> Implement -p/--portable

CHANGELOG.md, src/path_finders.rs
=> Include files untracked by git

flake.nix
Include completion scripts.
Run more integration tests.
=> Improve flake installation

Cargo.lock, Cargo.toml, flake.nix, src/output.rs
=> Bump lscolors version
